language: go
go:
- 1.9.x
- 1.10.x
- 1.11.x
- 1.12.x
- 1.13.x
- 1.14.x
env:
  global:
    secure: FEfqfOSiy5Cnol/OFNGzhS5vUeNBIetuUDQsjBryyPk93XbaF+J5G7QTDN4d+h6P6BvcTQ6xnsSMLJiC9/ukyxqvbiNdcofB4bDlgTwHuGWTH5xTbM0JYb9mOcgnVsv18i/H9e3qdfxQwrrJ8EtupgET7bx9nfXgFXDPXpCSw6sca5oQVJbL+eHsE23NwMPII8MXhOfsIX+WK3H61m/AsNtKNyiALcWyuWfuu1z62J582sG2NAAlyhrw5WShi9bmPcq8iKJvF71jSYWwRUPb0GplO3gFFouHIzyaKn7yKck0mE4xsbeY4dwOC5jrw97hq8eUWWAa7TwZnn290qkWGPKH3Y49ECP9Wa2bLtzvF+X/rZ01KwW9kkRvwX+VqpRoe22Dp+QXs8QHCxegxSMOvprAQBwXRQlQ3ULUxq7XFYJXtlHRDgvHcBCqLHU6Zwa0+HQVdyXcBpAyUFnAVNEXh9DmLlOaxAHO5ByS+m0rsYcWUxsj9Nvvz5lJem44sEQlvT4lHggRABCQwEp/TTfS4xMS01o/k2wfOex4VaWclGYMdh4YseL5yOCxHpZ9kcB72FKdkQVFwPZCSgCyhQIqfma+9KAZNhdCJyRzLjHQACDF3IWqUlFqye6/puTw/slKjpeLHfj3rDYSjBJcaV7q5YvAxcoEQklI8jzhrEAKss8=
